[package]
name = "port-explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_yaml = "0.9.34"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
once_cell = "1.19"
indicatif = "0.17"
threadpool = "1.8"
tempfile = "3.22.0"
clap = { version = "4.5", features = ["derive"] }
